### ISSUE TITLE
Demo not working in iphone IOS6 simumator

### ISSUE THREAD

**Issue by florent-andre** [dpa99c/cordova-diagnostic-plugin-example#1]
Hi,
Thanks for this repository.
I'm currently try to implementing diagnostic-plugin example with no success in one of my project.
So, looking at your repository I try to use this for simulation, and don't get cool results neither.
I checkout the code, do a $cordova build ios then open the xcode file in xcode and start the simulator for iphone6.
I simulate a location with the debug view.
Please find attached the printscreen I get.

Do you have any pointer on this ? 
Thanks.
![screen shot 2015-10-23 at 16 40 06](https://cloud.githubusercontent.com/assets/837462/10695692/537efd52-79a5-11e5-800c-b7ea1cbf8f41.png)
![screen shot 2015-10-23 at 16 40 24](https://cloud.githubusercontent.com/assets/837462/10695693/5381165a-79a5-11e5-8d4b-edd036926224.png)

**Comment by dpa99c** [comment]
Not sure why you are having these issues. Try to run Safari and connect the remote debugger (Develop>Simulator>index.html) to inspect the WebView, then go to "Resources" tab and click reload button (next to index.html) to see if there is an JS error.

It works fine for me. Here is screenshot from Simulator running iPhone 6 iOS 9.0:

![cordova-plugin-diagnostic](https://cloud.githubusercontent.com/assets/2345062/10701483/991c902a-79bb-11e5-8a19-adb15dfd3d3b.png)

**Comment by dpa99c** [comment]
@florent-andre Is this still and issue or can it be closed?

**Comment by florent-andre** [comment]
I have to try.
The project take delay so I will try again, but not immediatly.
As you want, I can re-open.
Thanks.
