### ISSUE TITLE
Example requires cordova-plugin-file

### ISSUE THREAD

**Issue by BobAchgill** [dpa99c/cordova-diagnostic-plugin-example#4]
The installation procedure for cordova-diagnostic-plugin-example does not say to install cordova-plugin-file.  Maybe append the install instructions to add in the cordova-plugin-file??

Not having the cordova-plugin-file installed results in this error when pressing the "Request external SD details" button.  

`TypeError: Cannnot set property 'externalSdCardDirectory' of undefined`

The `detail,filePath` is meant to be used with cordova-plugin-file... see lines below...

Line 274 - 276 of index.js assume that cordova-plugin-file is installed which it is not according to the installation procedure. 
```
                if(detail.canWrite){
                    $('#write-external-sd-file').css('display', 'block');
                    cordova.file.externalSdCardDirectory = detail.filePath;
```

**Comment by dpa99c** [comment]
cordova-plugin-file is [specified as a plugin dependency in the project config.xml](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/config.xml#L31 ) therefore running `cordova prepare` or any operation on which it depends (e.g. `cordova platform add android`) from the command-line will automatically add plugin dependencies to the project, including cordova-plugin-file. See the [Cordova documentation](https://cordova.apache.org/docs/en/latest/config_ref/#plugin) for details how the Cordova CLI plugin restore mechanism works.
